version: "3.8"

services:
  app:
    image: execucao-container
    build:
      context: .
      dockerfile: Dockerfile
    container_name: application
    command: python src/main.py
    volumes:
       - .:/app
    depends_on:
       - mongo 

  mongo:
    image: mongo #$ docker exec -it database bash
    container_name: mongo-test
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: lappis
      MONGO_INITDB_ROOT_PASSWORD: lappis

    
 
