name: .NET

on:
  push:
    branches: [ master ] 
  pull_request:
    branches: [ master ]

  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create parser_application network
        working-directory: .
        run: docker network create parser_application

      - name: Build da aplicacao
        working-directory: .
        run: docker-compose up -d

  poetry-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0 
      - name: Git Version
        id: version
        uses: codacy/git-version@2.7.1

      - name: Create parser_application network
        working-directory: .
        run: docker network create parser_application

      - name: Deploy poetry
        working-directory: .

        run: docker-compose run app bash -c "poetry add `cat requirements.txt`; poetry install; poetry version ${{ steps.version.outputs.version }}; poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}; poetry build; poetry publish"

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create parser_application network
        working-directory: .
        run: docker network create parser_application

      - name: Run pytest
        working-directory: .
        run : docker-compose run app bash -c "pytest -v"
    
  doxygen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create parser_application network
        working-directory: .
        run: docker network create parser_application

      - name: Build pages from doxygen
        working-directory: .
        run : docker-compose run app bash -c "doxygen doxygen.conf; sphinx-build -b html ./docs/source/ ./docs/build"

      - name: github-pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build
          force_orphan: true
      
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./docs/build/
